---
kind: pipeline
name: test_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y cmake build-essential 
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_trusty

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:trusty
  commands:
  - apt-get update
  - apt-get install -y gcc cmake3 build-essential git binutils-2.26
 
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_xenial

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:xenial
  commands:
  - apt-get update
  - apt-get install -y gcc cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master

---
kind: pipeline
name: build_bionic
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install -y gcc cmake build-essential
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
---
kind: pipeline
name: build_centos7
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ansible/centos7-ansible
  commands:
  - yum install -y gcc gcc-c++ make cmake
  - mkdir debug
  - cd debug
  - cmake .. 
  - make 
  trigger:
    event:
      - pull_request
  when:
    branch:
    - develop
    - master
